/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dslokzzuhzbhjrzlwqqe"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbG9renp1aHpiaGpyemx3cXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxODU2MjMsImV4cCI6MjA3Nzc2MTYyM30.GELgwZWmGwk-qK7RBTJt7Xyrfj-bXY6WFM3NXZH7eDI"